theme: jekyll-theme-midnight
show_downloads: true
title: mCTerminal Telemetri Yazılımı
logo: /mCTerminal_files/pngs/terminal_logo2.png
description: Windows için C# ile yazılmış telemetri programı.
show_downloads: true
